// src/lib/seed.ts
import { redis } from './redis';
import { Product } from '@/types';

const products: Product[] = [
  {
    id: '1',
    name: "Haldiram's Sev Bhujia",
    description: 'Spicy and crunchy snack made from chickpea flour',
    price: 21.6,
    originalPrice: 24,
    image: '/images/products/product-img-1.jpg',
    category: 'Snack & Munchies',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    badge: 'Sale',
    discount: 10,
  },
  {
    id: '2',
    name: 'NutriChoice Digestive',
    description: 'Healthy digestive biscuits with wheat and oats',
    price: 24,
    originalPrice: 24,
    image: '/images/products/product-img-2.jpg',
    category: 'Bakery & Biscuits',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
  {
    id: '3',
    name: 'Cadbury 5 Star Chocolate',
    description: 'Delicious chocolate with caramel and nougat',
    price: 35,
    originalPrice: 35,
    image: '/images/products/product-img-3.jpg',
    category: 'Bakery & Biscuits',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    badge: 'Buy 1 Get $4.00 Off',
  },
  {
    id: '4',
    name: 'Onion Flavour Potato',
    description: 'Crispy potato chips with onion flavor',
    price: 3,
    originalPrice: 5,
    image: '/images/products/product-img-4.jpg',
    category: 'Snack & Munchies',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    badge: 'Hot',
    discount: 40,
  },
  {
    id: '5',
    name: 'Salted Instant Popcorn',
    description: 'Ready to eat salted popcorn',
    price: 11.7,
    originalPrice: 18,
    image: '/images/products/product-img-5.jpg',
    category: 'Instant Food',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    discount: 35,
  },
  {
    id: '6',
    name: 'Blueberry Greek Yogurt',
    description: 'Creamy Greek yogurt with real blueberries',
    price: 14.4,
    originalPrice: 24,
    image: '/images/products/product-img-6.jpg',
    category: 'Dairy, Bread & Eggs',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    discount: 40,
  },
  {
    id: '7',
    name: 'Britannia Cheese Slices',
    description: 'Premium quality cheese slices',
    price: 24,
    originalPrice: 24,
    image: '/images/products/product-img-7.jpg',
    category: 'Dairy, Bread & Eggs',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
  {
    id: '8',
    name: "Kellogg's Original Cereals",
    description: 'Nutritious breakfast cereals',
    price: 29.75,
    originalPrice: 35,
    image: '/images/products/product-img-8.jpg',
    category: 'Instant Food',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    discount: 15,
  },
  {
    id: '9',
    name: 'Slurrp Millet Chocolate',
    description: 'Healthy millet chocolate for kids',
    price: 22,
    originalPrice: 25,
    image: '/images/products/product-img-9.jpg',
    category: 'Snack & Munchies',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
  {
    id: '10',
    name: 'Amul Butter - 500 g',
    description: 'Pure and fresh Amul butter',
    price: 13.5,
    originalPrice: 18,
    image: '/images/products/product-img-10.jpg',
    category: 'Dairy, Bread & Eggs',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
    discount: 25,
  },
  {
    id: '11',
    name: 'Roast Ground Coffee',
    description: '100% Organic Coffee Beans',
    price: 13.5,
    originalPrice: 18,
    image: '/images/products/product-img-11.jpg',
    category: 'Tea, Coffee & Drinks',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
  {
    id: '12',
    name: 'Crushed Tomatoes',
    description: 'Fresh crushed tomatoes',
    price: 13.5,
    originalPrice: 18,
    image: '/images/products/product-img-12.jpg',
    category: 'Fruits & Vegetables',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
  {
    id: '13',
    name: 'Golden Pineapple',
    description: 'Sweet and juicy golden pineapple',
    price: 14.4,
    originalPrice: 18,
    image: '/images/products/product-img-13.jpg',
    category: 'Fruits & Vegetables',
    rating: 4.3,
    reviewCount: 4,
    inStock: true,
  },
];

export async function seedProducts() {
  try {
    await redis.set('products', JSON.stringify(products));
    console.log('Products seeded successfully');
  } catch (error) {
    console.error('Error seeding products:', error);
  }
}